# Generated by Django 4.0.6 on 2025-01-03 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='matricula',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
