# Generated by Django 4.0.6 on 2025-01-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumnos', '0005_alter_estudiante_cedula'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='cedula',
            field=models.CharField(default=0, max_length=10, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='cedula',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
